version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - "./docker/entrypoint.sh:/entrypoint.sh"
      - ".:/www/challenge"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env

  db:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    volumes:
      - "sql:/var/lib/mysql"
      - "./docker/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  sql:
